# Use the official PostgreSQL image from the Docker Hub
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=pgidb

# Copy the database schema to the initialization directory
COPY ./dbschema/db_schema.sql /docker-entrypoint-initdb.d/db_schema.sql

# Expose the PostgreSQL port
EXPOSE 5432

# Start the PostgreSQL server
CMD ["postgres"]
