# Stage 1: Build the application
FROM gradle:8.2.1-jdk21 AS build
WORKDIR /app
COPY . .
RUN ./gradlew clean build --no-daemon

# Stage 2: Run the application
FROM openjdk:21-slim
WORKDIR /app
COPY --from=build /app/pgi/build/libs/pgi-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
